In [1]:
# !pip install pandas-datareader

### Evaluating the price of TESLA share on 4th of December 2022 using FCFF and FCFE

In [2]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
from pandas_datareader import data as web
import datetime as dt
import statsmodels.formula.api as smf
pd.set_option('display.max_columns', 500)
import warnings
warnings.simplefilter('ignore')

<p>Unlevered free cash flow - UFCF - FCFF:</p> 
<p>EBIT*(1-eff.tax rate) + NCC - FCInv - increase in WCInv</p>
<p>EBIT = Net Income + tax expense + interest expense</p> 
<p>NCC = depr/amort + abs(Asset WriteDown(impairment charges)) + Gain (Loss) On Sale Of Invest. + Gain (Loss) On Sale Of Assets + (optional Stock based Compensation )</p>   
<p>FCInv = CAPEX - (optional(Proceeds from sales of long term assets))</p>   
<p>or</p>   
<p>FCInv = ending Net PP&E - beginning Net PP&E + Depreciation - gain on sale + loss on sale</p>   
<p>WCInv = sum of changes in Accounts Receivables, Inventory and Payables</p>   
<p>eff.tax rate = income Tax Expense / Earnings before Tax</p>   
    
<p>Levered free cash flow - LFCF - FCFE:</p>   
<p>FCFE = FCFF - Interest Expense*(1- stat.tax rate) + net borrowing(dept repayment or repayments of term debt from CF )</p>   
    
<p>EBITDA -  irrespective of leverage</p>

The whole process is based on validation from [site.financialmodelingprep.com](site.financialmodelingprep.com)
### There are plenty of assumptions, but conceptually it should be robust

In [3]:
# download your own personal key from site.financialmodelingprep.com? in order to be able 
# to use api
key = pd.read_csv('keyfinmodeling.txt', header=None)[0][0]
tickers = ['AAPL']

# download and use finnancial statements from the site
def get_income_statement(ticker, limit, key, period):

    URL = 'https://financialmodelingprep.com/api/v3/income-statement/'
    try:
        r = requests.get(
            '{}{}?period={}?limit={}&apikey={}'.format(URL,
                                                       ticker,
                                                       period,
                                                       limit,
                                                       key))
        incomeStatement = pd.DataFrame.from_dict(r.json()).transpose()
        incomeStatement.columns = incomeStatement.iloc[0]
#         return incomeStatement[1:]
        incomeStatement[1:].to_excel(ticker+' Income Statement.xlsx')
    except requests.exceptions.HTTPError as e:
        # We want a 200 value
        print('Requesting Income statement sheet ERROR: ', str(e))

def get_balance_sheet(ticker, limit, key, period):
    
    URL = 'https://financialmodelingprep.com/api/v3/balance-sheet-statement/'
    try:
        r = requests.get(
            '{}{}?period={}&?limit={}&apikey={}'.format(URL,
                                                        ticker,
                                                        period,
                                                        limit,
                                                        key))
        balanceSheet = pd.DataFrame.from_dict(r.json()).transpose()
        balanceSheet.columns = balanceSheet.iloc[0]
#         return balanceSheet[1:]
        balanceSheet[1:].to_excel(ticker+' Balance Sheet.xlsx')
    except requests.exceptions.HTTPError as e:
        # We want a 200 value
        print('Requesting Balance sheet statement ERROR: ', str(e))
        
def get_cash_flow_statement(ticker, limit, key, period):

    URL = 'https://financialmodelingprep.com/api/v3/cash-flow-statement/'
    try:
        r = requests.get(
            '{}{}?period={}&?limit={}&apikey={}'.format(URL,
                                                        ticker,
                                                        period,
                                                        limit,
                                                        key))
        cashFlow = pd.DataFrame.from_dict(r.json()).transpose()
        cashFlow.columns = cashFlow.iloc[0]
#         return cashFlow[1:]
        cashFlow.to_excel(ticker+' Cash Flow.xlsx')
    except requests.exceptions.HTTPError as e:
        print('Requesting Cash flow statement ERROR: ', str(e))
        
# get_income_statement(tickers[0], 5, key, 'annual')
# get_balance_sheet(tickers[0], 5, key, 'annual')
# get_cash_flow_statement(tickers[0], 5, key, 'annual')  

inc_s = pd.read_excel(tickers[0]+' Income Statement.xlsx',index_col='Unnamed: 0')
bs = pd.read_excel(tickers[0]+' Balance Sheet.xlsx', index_col='Unnamed: 0')
cf = pd.read_excel(tickers[0]+' Cash Flow.xlsx', index_col='Unnamed: 0')

# inc_s
# bs
# cf

In [5]:
# use specific statement location to grab data and formulas to calculate fcff, fcfe and other
rev = inc_s.loc['revenue']
ebit = inc_s.loc['netIncome'] + inc_s.loc['incomeTaxExpense'] + inc_s.loc['interestExpense']
stat_tax_rate = 0.21
eff_tax_rate = (inc_s.loc['incomeTaxExpense'] / inc_s.loc['incomeBeforeTax'])
ncc = cf.loc['depreciationAndAmortization']
fcinv = cf.loc['capitalExpenditure']
tax_exp = inc_s.loc['incomeTaxExpense']
wcinv = (abs(bs.loc['netReceivables']) + abs(bs.loc['inventory']) - abs(bs.loc['accountPayables']) -
         (abs(bs.loc['netReceivables'].shift(-1)) + abs(bs.loc['inventory'].shift(-1)) - abs(bs.loc['accountPayables'].shift(-1))))
fcff = ebit * (1-eff_tax_rate) + ncc - abs(fcinv) - wcinv
net_bor = abs(cf.loc['debtRepayment'])
fcfe = fcff - inc_s.loc['interestExpense'][0]*(1-stat_tax_rate) + net_bor

# convert all financial statements in 1 dataframe and calculate growth rates
df = pd.DataFrame({'Revenue':  inc_s.loc['revenue'] / 1000000,        
                   'Revenue_%_change': (rev / rev.shift(-1)) - 1,
                   'Depretiation': cf.loc['depreciationAndAmortization'] / 1000000,
                   'Depretiation_%_revenue': (cf.loc['depreciationAndAmortization'] / rev),
                   'EBIT': ebit/1000000, 
                   'EBIT_%_revenue': (ebit / rev),  
                   'FCInv(CAPEX)': fcinv/1000000,
                   'FCInv(CAPEX)_%_revenue': fcinv / rev,
                   'Account_receivables': bs.loc['netReceivables'] / 1000000,
                   'Account_receivables_%_revenue': bs.loc['netReceivables'] / rev,
                   'Inventory': bs.loc['inventory'] / 1000000,
                   'Inventory_%_revenue': bs.loc['inventory']/rev,
                   'Account_Payables': bs.loc['accountPayables'] / 1000000,
                   'Account_Payables_%_revenue': bs.loc['accountPayables']/rev,
                   'Interest_Expense': tax_exp / 1000000,
                   'Interest_Expense_%_change': (tax_exp / tax_exp.shift(-1)) - 1,  
                   'Net_borrowings': net_bor/1000000, 
                   'Net_borrowings_%_change': (net_bor / net_bor.shift(-1)) - 1,
                   'Non_Cash_Charges': ncc/1000000,
                   'Eff_tax_rate': eff_tax_rate,                   
                   'Av_Eff_tax_rate': eff_tax_rate.mean(),
                   'FCFF': fcff/1000000, 
                   'FCFE': fcfe/1000000})

df = df.sort_index()
df = df.fillna(0)
df

,Revenue,Revenue_%_change,Depretiation,Depretiation_%_revenue,EBIT,EBIT_%_revenue,FCInv(CAPEX),FCInv(CAPEX)_%_revenue,Account_receivables,Account_receivables_%_revenue,Inventory,Inventory_%_revenue,Account_Payables,Account_Payables_%_revenue,Interest_Expense,Interest_Expense_%_change,Net_borrowings,Net_borrowings_%_change,Non_Cash_Charges,Eff_tax_rate,Av_Eff_tax_rate,FCFF,FCFE
2018-09-29,265595.0,0.000000,10903.0,0.041051,76143.0,0.286688,-13313.0,-0.050125,48995.0,0.184473,3956.0,0.014895,55888.0,0.210426,13372.0,0.000000,6500.0,0.000000,10903.0,0.183422,0.156442,0.000000,0.000000
2019-09-28,260174.0,-0.020411,12547.0,0.048225,69313.0,0.266410,-10495.0,-0.040338,45804.0,0.176051,4106.0,0.015782,46236.0,0.177712,10481.0,-0.216198,8805.0,0.354615,12547.0,0.159438,0.156442,53702.848396,60192.358396
2020-09-26,274515.0,0.055121,11056.0,0.040275,69964.0,0.254864,-7309.0,-0.026625,37445.0,0.136404,4061.0,0.014793,42296.0,0.154075,9680.0,-0.076424,12629.0,0.434299,11056.0,0.144282,0.156442,68080.478827,78393.988827
2021-09-25,365817.0,0.332594,11284.0,0.030846,111852.0,0.305759,-11085.0,-0.030302,51506.0,0.140797,6580.0,0.017987,54763.0,0.149701,14527.0,0.500723,8750.0,-0.307150,11284.0,0.133023,0.156442,93059.155201,99493.665201
2022-09-24,394328.0,0.077938,11104.0,0.028159,122034.0,0.309473,-10708.0,-0.027155,60932.0,0.154521,4946.0,0.012543,64115.0,0.162593,19300.0,0.328561,9543.0,0.090629,11104.0,0.162045,0.156442,104215.047228,111442.557228

In [6]:
# show a better view
df.T

,2018-09-29,2019-09-28,2020-09-26,2021-09-25,2022-09-24
Revenue,265595.000000,260174.000000,274515.000000,365817.000000,394328.000000
Revenue_%_change,0.000000,-0.020411,0.055121,0.332594,0.077938
Depretiation,10903.000000,12547.000000,11056.000000,11284.000000,11104.000000
Depretiation_%_revenue,0.041051,0.048225,0.040275,0.030846,0.028159
EBIT,76143.000000,69313.000000,69964.000000,111852.000000,122034.000000
EBIT_%_revenue,0.286688,0.266410,0.254864,0.305759,0.309473
FCInv(CAPEX),-13313.000000,-10495.000000,-7309.000000,-11085.000000,-10708.000000
FCInv(CAPEX)_%_revenue,-0.050125,-0.040338,-0.026625,-0.030302,-0.027155
Account_receivables,48995.000000,45804.000000,37445.000000,51506.000000,60932.000000
Account_receivables_%_revenue,0.184473,0.176051,0.136404,0.140797,0.154521
Inventory,3956.000000,4106.000000,4061.000000,6580.000000,4946.000000
Inventory_%_revenue,0.014895,0.015782,0.014793,0.017987,0.012543
Account_Payables,55888.000000,46236.000000,42296.000000,54763.000000,64115.000000
Account_Payables_%_revenue,0.210426,0.177712,0.154075,0.149701,0.162593
Interest_Expense,13372.000000,10481.000000,9680.000000,14527.000000,19300.000000
Interest_Expense_%_change,0.000000,-0.216198,-0.076424,0.500723,0.328561
Net_borrowings,6500.000000,8805.000000,12629.000000,8750.000000,9543.000000
Net_borrowings_%_change,0.000000,0.354615,0.434299,-0.307150,0.090629
Non_Cash_Charges,10903.000000,12547.000000,11056.000000,11284.000000,11104.000000
Eff_tax_rate,0.183422,0.159438,0.144282,0.133023,0.162045
Av_Eff_tax_rate,0.156442,0.156442,0.156442,0.156442,0.156442
FCFF,0.000000,53702.848396,68080.478827,93059.155201,104215.047228
FCFE,0.000000,60192.358396,78393.988827,99493.665201,111442.557228

In [7]:
# create dataframe to calculate CAGR and Average growth % from revenue, 
# we will use % from revenue in creating forecasts

growth_df =  pd.DataFrame(data=0, index=['growth'], columns=df.columns)

cagr_list = ['Revenue','EBIT', 'Depretiation', 'Non_Cash_Charges','FCInv(CAPEX)',
             'Account_receivables','Inventory','Account_Payables','Net_borrowings', 
             'WCInv','FCFF','FCFE', 'Interest_Expense']
av_list = ['Revenue_%_change','EBIT_%_revenue', 'Depretiation_%_revenue',
           'Eff_tax_rate','FCInv(CAPEX)_%_revenue','Account_receivables_%_revenue',
           'Inventory_%_revenue','Account_Payables_%_revenue',
           'Net_borrowings_%_change', 'Av_Eff_tax_rate','Interest_Expense_%_change']

for x in df.columns:
# use cagr list    
    if x in cagr_list:
        if df[x][0] != 0:
            growth_df[x]['growth'] = round(((df[x][len(df)-1]) / (df[x][0])) ** (1/len(df[x])) - 1, 4)
        else:
            growth_df[x]['growth'] = round(((df[x][len(df)-1]) / (df[x][1]))** (1/len(df[x])) - 1, 4)
# use average list        
    elif x in av_list:
        if df[x][0] != 0:
            growth_df[x]['growth'] = df[x].mean() 
        else:
            growth_df[x]['growth'] = df[x][1:].mean()
            
    
               
growth_df = growth_df.astype('float')

In [8]:
# concatinating
result = pd.concat([df, growth_df], axis=0)
result

,Revenue,Revenue_%_change,Depretiation,Depretiation_%_revenue,EBIT,EBIT_%_revenue,FCInv(CAPEX),FCInv(CAPEX)_%_revenue,Account_receivables,Account_receivables_%_revenue,Inventory,Inventory_%_revenue,Account_Payables,Account_Payables_%_revenue,Interest_Expense,Interest_Expense_%_change,Net_borrowings,Net_borrowings_%_change,Non_Cash_Charges,Eff_tax_rate,Av_Eff_tax_rate,FCFF,FCFE
2018-09-29,265595.0000,0.000000,10903.0000,0.041051,76143.0000,0.286688,-13313.0000,-0.050125,48995.0000,0.184473,3956.0000,0.014895,55888.0000,0.210426,13372.0000,0.000000,6500.0000,0.000000,10903.0000,0.183422,0.156442,0.000000,0.000000
2019-09-28,260174.0000,-0.020411,12547.0000,0.048225,69313.0000,0.266410,-10495.0000,-0.040338,45804.0000,0.176051,4106.0000,0.015782,46236.0000,0.177712,10481.0000,-0.216198,8805.0000,0.354615,12547.0000,0.159438,0.156442,53702.848396,60192.358396
2020-09-26,274515.0000,0.055121,11056.0000,0.040275,69964.0000,0.254864,-7309.0000,-0.026625,37445.0000,0.136404,4061.0000,0.014793,42296.0000,0.154075,9680.0000,-0.076424,12629.0000,0.434299,11056.0000,0.144282,0.156442,68080.478827,78393.988827
2021-09-25,365817.0000,0.332594,11284.0000,0.030846,111852.0000,0.305759,-11085.0000,-0.030302,51506.0000,0.140797,6580.0000,0.017987,54763.0000,0.149701,14527.0000,0.500723,8750.0000,-0.307150,11284.0000,0.133023,0.156442,93059.155201,99493.665201
2022-09-24,394328.0000,0.077938,11104.0000,0.028159,122034.0000,0.309473,-10708.0000,-0.027155,60932.0000,0.154521,4946.0000,0.012543,64115.0000,0.162593,19300.0000,0.328561,9543.0000,0.090629,11104.0000,0.162045,0.156442,104215.047228,111442.557228
growth,0.0822,0.111310,0.0037,0.037711,0.0989,0.284639,-0.0426,-0.034909,0.0446,0.158449,0.0457,0.015200,0.0278,0.170901,0.0761,0.134165,0.0798,0.143098,0.0037,0.156442,0.156442,0.141800,0.131100

### Assumptions:
1. In my calculations revenue grows with a certain % - I know that it is not right, 
because revenue could be easily manipulated, and to be more accurate 
you need to obtain sales data for each year and break the structure of sales
2. Create macroeconomical analysis of economy involving analysis of ability to be bought
in future by purchasers
3. Make adjustments for competitors
4. Look for news to get the sentiment and the history of sales
5. Make a forecast

6. Theyre are some items that shouldn't be calculated as % from revenue - 
interest expense, income taxes and other, but here I did it for the sake of simplicity
in real world you need to watch for company history of paying taxes to see some deferred 
tax assets for example. Or better calculate revenue, cogs, look for company bond issuance 
to forecast companies interest repayment.

In [9]:
# break data to ease calculations
result = result.T
r1 = result[:]['Revenue':'Net_borrowings_%_change']
r2 = result[:]['Non_Cash_Charges':]

# we will shift data backwards, because we will use average % change from revenue
r1.growth = r1['growth'].shift(-1)

# drop every second item from the index starting from 1
r1 = r1.drop(index=r1.index[1::2])

In [10]:
forecasts = ['2023', '2024', '2025', '2026', '2027']

# create df for forecasting data
forecast_df =  pd.DataFrame(data=0, index=r1.index, columns=forecasts)

# unfortunately i am not abe to create a loop for diefferent ormulas in one line
# I hope that eventually I will become a beter python user
forecast_df['2023']['Revenue'] = r1['2022-09-24']['Revenue'] * (1 + r1['growth']['Revenue'])
forecast_df['2024']['Revenue'] = forecast_df['2023']['Revenue'] * (1 + r1['growth']['Revenue'])
forecast_df['2025']['Revenue'] = forecast_df['2024']['Revenue'] * (1 + r1['growth']['Revenue'])
forecast_df['2026']['Revenue'] = forecast_df['2025']['Revenue'] * (1 + r1['growth']['Revenue'])
forecast_df['2027']['Revenue'] = forecast_df['2026']['Revenue'] * (1 + r1['growth']['Revenue'])

# loop to calculate everything as % from revenue
for x in forecast_df.columns:
    for y in forecast_df.index[1:]:
        forecast_df[x][y] = forecast_df[x]['Revenue'] * abs(r1['growth'][y])

In [11]:
# bring 2022 year to be able to make calculations
res_forecast = pd.concat([r1['2022-09-24'], forecast_df ], axis=1)
res_forecast

,2022-09-24,2023,2024,2025,2026,2027
Revenue,394328.0,438220.822330,486999.373932,541207.487469,601449.529859,668397.140363
Depretiation,11104.0,16525.888482,18365.392364,20409.652229,22681.459555,25206.142748
EBIT,122034.0,124734.767537,138619.049125,154048.796175,171196.035126,190251.940751
FCInv(CAPEX),-10708.0,15297.921978,17000.740371,18893.100225,20996.099483,23333.184509
Account_receivables,60932.0,69435.782426,77164.709769,85753.947399,95299.256830,105907.058833
Inventory,4946.0,6660.953080,7402.386683,8226.349586,9142.028160,10159.631318
Account_Payables,64115.0,74892.504666,83228.822151,92493.058785,102788.501655,114229.934779
Interest_Expense,19300.0,58794.085140,65338.480499,72611.335371,80693.734903,89675.789865
Net_borrowings,9543.0,62708.571453,69688.689997,77445.768593,86066.291003,95646.367538

In [12]:
# make forecasts and calculate
ebit_f = res_forecast.loc['EBIT']
stat_tax_rate = 0.21
eff_tax_rate_f = result.loc['Av_Eff_tax_rate'][0]
ncc_f = res_forecast.loc['Depretiation']
fcinv_f = res_forecast.loc['FCInv(CAPEX)']
wcinv_f = (abs(res_forecast.loc['Account_receivables']) + abs(res_forecast.loc['Inventory']) - 
         abs(res_forecast.loc['Account_Payables']) - (abs(res_forecast.loc['Account_receivables'].shift(1)) + 
        abs(res_forecast.loc['Inventory'].shift(1)) - abs(res_forecast.loc['Account_Payables'].shift(1))))
fcff_f = ebit_f * (1-eff_tax_rate_f) + ncc_f - abs(fcinv_f) - wcinv_f
tax_exp_f = res_forecast.loc['Interest_Expense']
net_bor_f = abs(res_forecast.loc['Net_borrowings'])
fcfe_f = fcff_f - tax_exp_f*(1-stat_tax_rate) + net_bor_f
forecast_dcf = pd.DataFrame({
    'FCFF': fcff_f,
    'FCFE': fcfe_f
})
forecast_dcf = forecast_dcf.dropna().T
forecast_dcf

               2023           2024          2025           2026           2027
FCFF  107007.770456  118163.842774  131316.71185  145933.632541  162177.569074
FCFE  123269.014648  136235.133177  151399.52550  168251.872971  186980.062618

In [13]:
# concatenate in 1 df past, growth and future
fin_2 = pd.concat([r2,forecast_dcf], axis=1)
fin_1 = pd.concat([r1,forecast_df], axis=1)
fin_3 = pd.concat([fin_1,fin_2], axis=0)
fin_3.loc['Non_Cash_Charges']['2023':'2027'] = ncc_f[1:]
fin_3

,2018-09-29,2019-09-28,2020-09-26,2021-09-25,2022-09-24,growth,2023,2024,2025,2026,2027
Revenue,265595.000000,260174.000000,274515.000000,365817.000000,394328.000000,0.111310,438220.822330,486999.373932,541207.487469,601449.529859,668397.140363
Depretiation,10903.000000,12547.000000,11056.000000,11284.000000,11104.000000,0.037711,16525.888482,18365.392364,20409.652229,22681.459555,25206.142748
EBIT,76143.000000,69313.000000,69964.000000,111852.000000,122034.000000,0.284639,124734.767537,138619.049125,154048.796175,171196.035126,190251.940751
FCInv(CAPEX),-13313.000000,-10495.000000,-7309.000000,-11085.000000,-10708.000000,-0.034909,15297.921978,17000.740371,18893.100225,20996.099483,23333.184509
Account_receivables,48995.000000,45804.000000,37445.000000,51506.000000,60932.000000,0.158449,69435.782426,77164.709769,85753.947399,95299.256830,105907.058833
Inventory,3956.000000,4106.000000,4061.000000,6580.000000,4946.000000,0.015200,6660.953080,7402.386683,8226.349586,9142.028160,10159.631318
Account_Payables,55888.000000,46236.000000,42296.000000,54763.000000,64115.000000,0.170901,74892.504666,83228.822151,92493.058785,102788.501655,114229.934779
Interest_Expense,13372.000000,10481.000000,9680.000000,14527.000000,19300.000000,0.134165,58794.085140,65338.480499,72611.335371,80693.734903,89675.789865
Net_borrowings,6500.000000,8805.000000,12629.000000,8750.000000,9543.000000,0.143098,62708.571453,69688.689997,77445.768593,86066.291003,95646.367538
Non_Cash_Charges,10903.000000,12547.000000,11056.000000,11284.000000,11104.000000,0.003700,16525.888482,18365.392364,20409.652229,22681.459555,25206.142748
Eff_tax_rate,0.183422,0.159438,0.144282,0.133023,0.162045,0.156442,NaN,NaN,NaN,NaN,NaN
Av_Eff_tax_rate,0.156442,0.156442,0.156442,0.156442,0.156442,0.156442,NaN,NaN,NaN,NaN,NaN
FCFF,0.000000,53702.848396,68080.478827,93059.155201,104215.047228,0.141800,107007.770456,118163.842774,131316.711850,145933.632541,162177.569074
FCFE,0.000000,60192.358396,78393.988827,99493.665201,111442.557228,0.131100,123269.014648,136235.133177,151399.525500,168251.872971,186980.062618

### WACC, cost of equity, cost of debt calculations
<p> Cost of equity
Re = Rf + b*(Rm - Rf)</p>
<p>AAPL is the USA's company so let's use USA 10 year Treasury rates</p> 
<p> Rf = 0.0371</p>

[https://ycharts.com/indicators/10_year_treasury_rate](https://ycharts.com/indicators/10_year_treasury_rate)

In [14]:
tr10 = pd.read_excel('DGS10.xls', parse_dates=True)

In [15]:
# unfortunately you need to pay to see the whole historical data for 10 Year Treasury Rate
# thus i have only 4 years it will suffice for us
tr10 = pd.read_excel('DGS10.xls', parse_dates=True)
# some data is missing let's fill it with median
tr10 = tr10.fillna(tr10.DGS10.median())
tr10 = tr10.rename(columns = {"observation_date": "Date", "DGS10": "10_Year_Rate"})
tr10.head()

        Date  10_Year_Rate
0 2017-11-24          2.34
1 2017-11-27          2.32
2 2017-11-28          2.34
3 2017-11-29          2.37
4 2017-11-30          2.42

In [16]:
def get_price_from_yahoo(ticker, syear, smonth, sday, eyear, emonth, eday):
    # define time periods to use
    start = dt.datetime(syear, smonth, sday)
    end = dt.datetime(eyear, emonth, eday)
    # read data 
    df = web.DataReader(ticker, 'yahoo', start, end)
    df = df.reset_index()
    price = df['Adj Close'][0]
    return price

def save_to_xlsx_from_yahoo(ticker, syear, smonth, sday, eyear, emonth, eday):
    # define time periods to use
    start = dt.datetime(syear, smonth, sday)
    end = dt.datetime(eyear, emonth, eday)
    # save data 
    df = web.DataReader(ticker, 'yahoo', start, end)
    df.to_excel(ticker + '.xlsx')

def save_to_csv_from_yahoo(ticker, syear, smonth, sday, eyear, emonth, eday):
    # define time periods to use
    start = dt.datetime(syear, smonth, sday)
    end = dt.datetime(eyear, emonth, eday)
    # save data 
    df = web.DataReader(ticker, 'yahoo', start, end)
    df.to_csv(ticker + '.csv')

def get_df_from_yahoo(ticker, syear, smonth, sday, eyear, emonth, eday):
    # define time periods to use
    start = dt.datetime(syear, smonth, sday)
    end = dt.datetime(eyear, emonth, eday)
    # read  data 
    df = web.DataReader(ticker, 'yahoo', start, end)
    df = df.reset_index()
    return df 

def get_df_from_xlsx(ticker):
    try:
        df = pd.read_excel(ticker + '.xlsx', parse_dates=True)
    except FileNotFound:
        print('File does not exist')
    else:
        return df

### calculating 5 year beta

In [17]:
# get price data for our company
save_to_xlsx_from_yahoo(tickers[0], 2017, 11, 26, 2022, 11, 26)
aapl_p = get_df_from_xlsx(tickers[0])
aapl_p = aapl_p[['Date', 'Adj Close']]
aapl_p['Date'] = pd.to_datetime(aapl_p.Date)
aapl_p = aapl_p.rename(columns = {"Adj Close": "AAPL_Price"})

# get price data for sp500 company
save_to_xlsx_from_yahoo('^GSPC', 2017, 11, 26, 2022, 11, 26)
sp500 = get_df_from_xlsx('^GSPC')
sp500 = sp500[['Date', 'Adj Close']]
sp500['Date'] = pd.to_datetime(sp500.Date)
sp500 = sp500.rename(columns = {"Adj Close": "SP500_Price"})

# merge data in 1 df
merged_df = pd.merge(left=tr10, right=aapl_p, left_on='Date',right_on='Date')
beta_df = pd.merge(left=merged_df, right=sp500, left_on='Date',right_on='Date')
beta_df['AAPL_Daily_returns'] = beta_df['AAPL_Price'].pct_change()
beta_df['SP500_Daily_returns'] = beta_df['SP500_Price'].pct_change()
beta_df = beta_df[1:]
beta_df['Excess_Return_AAPL'] = beta_df['AAPL_Daily_returns'] - beta_df['10_Year_Rate'].astype('float')/100
beta_df['Excess_Return_SP500'] = beta_df['SP500_Daily_returns'] - beta_df['10_Year_Rate'].astype('float')/100
beta_df.head()

,Date,10_Year_Rate,AAPL_Price,SP500_Price,AAPL_Daily_returns,SP500_Daily_returns,Excess_Return_AAPL,Excess_Return_SP500
1,2017-11-28,2.34,41.143063,2627.040039,-0.005859,0.009849,-0.029259,-0.013551
2,2017-11-29,2.37,40.289619,2626.070068,-0.020743,-0.000369,-0.044443,-0.024069
3,2017-11-30,2.42,40.853031,2647.580078,0.013984,0.008191,-0.010216,-0.016009
4,2017-12-01,2.37,40.662857,2642.219971,-0.004655,-0.002025,-0.028355,-0.025725
5,2017-12-04,2.37,40.365696,2639.439941,-0.007308,-0.001052,-0.031008,-0.024752

CFA says regress excessive returns, but in the Internet you may notice recommendation 
to regress returns, i did both to test the results

In [18]:
# beta with regression of returns
results1 = smf.ols('AAPL_Daily_returns ~ SP500_Daily_returns', data=beta_df).fit()
results1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:     AAPL_Daily_returns   R-squared:                       0.638
Model:                            OLS   Adj. R-squared:                  0.638
Method:                 Least Squares   F-statistic:                     2213.
Date:                Sun, 04 Dec 2022   Prob (F-statistic):          2.97e-279
Time:                        09:32:49   Log-Likelihood:                 3715.7
No. Observations:                1257   AIC:                            -7427.
Df Residuals:                    1255   BIC:                            -7417.
Df Model:                           1
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               0.0007      0.000      1.996      0.046    1.22e-05       0.001
SP500_Daily_returns     1.2224      0.026     47.039      0.000       1.171       1.273
==============================================================================
Omnibus:                      197.291   Durbin-Watson:                   1.871
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1633.745
Skew:                           0.459   Prob(JB):                         0.00
Kurtosis:                       8.509   Cond. No.                         73.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [19]:
beta_reg_1 = results1.params['SP500_Daily_returns']
beta_reg_1

1.2223582325534361

In [20]:
# beta with regression of excessive returns
results2 = smf.ols('Excess_Return_AAPL ~ Excess_Return_SP500', data=beta_df).fit()
results2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:     Excess_Return_AAPL   R-squared:                       0.699
Model:                            OLS   Adj. R-squared:                  0.699
Method:                 Least Squares   F-statistic:                     2919.
Date:                Sun, 04 Dec 2022   Prob (F-statistic):               0.00
Time:                        09:32:49   Log-Likelihood:                 3710.9
No. Observations:                1257   AIC:                            -7418.
Df Residuals:                    1255   BIC:                            -7408.
Df Model:                           1
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               0.0042      0.001      7.569      0.000       0.003       0.005
Excess_Return_SP500     1.1723      0.022     54.025      0.000       1.130       1.215
==============================================================================
Omnibus:                      179.257   Durbin-Watson:                   1.872
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1492.837
Skew:                           0.371   Prob(JB):                         0.00
Kurtosis:                       8.287   Cond. No.                         60.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [21]:
beta_reg_2 = results2.params['Excess_Return_SP500']
beta_reg_2

1.1723179380719504

In [22]:
# won't cahnge if it is 252 days or 982 days
# beta with formula: COVi,mkt/(mktvar) in daily excess returns
form_beta = beta_df[['Excess_Return_AAPL', 'Excess_Return_SP500']]
form_beta
cov = form_beta.cov() * 252
cov_vs_market = cov.iloc[0,1]
sp500_var = form_beta['Excess_Return_SP500'].var() * 252
beta1 = cov_vs_market / sp500_var
beta1

1.1723179380719504

In [23]:
# won't cahnge if it is 252 days or 982 days
# beta with formula: COVi,mkt/(mktvar) in daily returns
form_beta = beta_df[['AAPL_Daily_returns', 'SP500_Daily_returns']]
form_beta
cov = form_beta.cov() * 252
cov_vs_market = cov.iloc[0,1]
sp500_var = form_beta['SP500_Daily_returns'].var() * 252
beta2 = cov_vs_market / sp500_var
beta2

1.222358232553437

<p> Aswath Damodaran calculates beta for AAPL (Computers/Peripherals) that is 1.29 
and Unlevered beta corrected for cash is 1.25</p>
<p>on yahoo finance site beta is 1.25</p>
<p>on financialmodelingprep site beta is 1.247</p>

In [24]:
# taking beta as 1.25
# in between of calculations and estimations
beta = 1.25

In [25]:
# risk free rate - average risk free rate for given period
rf_rate = beta_df['10_Year_Rate'].astype('float').mean() / 100
rf_rate

0.02038989657915673

In [26]:
# we can take equity risk premium(4.59%) from here http://pages.stern.nyu.edu/~adamodar/
# or
# google market return of S&P500 that is 7.99 % in 2022
# or
# calculate expected market return by ourselves

# in case of Internet shutdown
# save_to_csv_from_yahoo('^GSPC', 1980, 1, 1, 2022, 11, 25)

In [27]:
# no data prior to 1980 year exists on yahoo fin site, and unlucky years could severely bias 
# average historical return downward
market_ret = get_df_from_yahoo('^GSPC', 1980, 1, 1, 2022, 11, 25)

years = [x for x in range(42)]
hist_calc = market_ret.loc[(market_ret['Date'] == '1980-01-02')]
for x in years:
    date1 = dt.datetime(1980+x,1,1)
    date2 = dt.datetime(1980+x,1,2)
    date3 = dt.datetime(1980+x,1,3)
    date4 = dt.datetime(1980+x,1,4)
    if len(market_ret.loc[(market_ret['Date'] == date1)]) == 1:
        hist_calc = pd.concat([hist_calc, market_ret.loc[(market_ret['Date'] == date1)]], axis=0)
    elif (len(market_ret.loc[(market_ret['Date'] == date1)]) == 0) and (len(market_ret.loc[(market_ret['Date'] == date2)]) == 1):
        hist_calc = pd.concat([hist_calc, market_ret.loc[(market_ret['Date'] == date2)]], axis=0)
    elif (len(market_ret.loc[(market_ret['Date'] == date1)]) == 0) and (len(market_ret.loc[(market_ret['Date'] == date2)]) == 1) and (len(market_ret.loc[(market_ret['Date'] == date3)]) == 1):
        hist_calc = pd.concat([hist_calc, market_ret.loc[(market_ret['Date'] == date3)]], axis=0)
    else:
        hist_calc = pd.concat([hist_calc, market_ret.loc[(market_ret['Date'] == date4)]], axis=0)
hist_calc = pd.concat([hist_calc, market_ret.iloc[-1:]], axis=0)
hist_calc.head(3)

          Date        High         Low  Open       Close    Volume   Adj Close
0   1980-01-02  108.430000  105.290001   0.0  105.760002  40610000  105.760002
0   1980-01-02  108.430000  105.290001   0.0  105.760002  40610000  105.760002
253 1981-01-02  137.100006  134.610001   0.0  136.339996  28870000  136.339996

In [28]:
hist_calc['yearly_returns'] = hist_calc['Adj Close'].pct_change()
hist_calc.dropna(inplace=True)
hist_calc.tail(3)

,Date,High,Low,Open,Close,Volume,Adj Close,yearly_returns
10087,2020-01-02,3258.139893,3235.530029,3244.669922,3257.850098,3459930000,3257.850098,0.297933
10340,2021-01-04,3769.989990,3662.709961,3764.610107,3700.649902,5015000000,3700.649902,0.135918
10818,2022-11-25,4034.020020,4020.760010,4023.340088,4026.120117,1706460000,4026.120117,0.087949

In [29]:
# average return
hist_calc.yearly_returns.mean()

0.09937806345654418

In [30]:
# geometric mean return
geom_mean = 1
for year_return in range(len(hist_calc)):
    geom_mean *= (1 + hist_calc['yearly_returns'].iloc[year_return])      

market_return = geom_mean ** (1/len(hist_calc)) - 1
market_return

0.08832180870940487

In [31]:
#CAPM calculation - cost of equity
expected_rate_return_calc = rf_rate + beta * (market_return - rf_rate)
expected_rate_return_calc

0.1053047867419669

In [32]:
# capm according to Aswath Damodaran risk premium
market_risk_prem = 0.0459
expected_rate_return_damod = rf_rate + beta * (market_risk_prem)
expected_rate_return_damod

0.07776489657915674

In [33]:
# according to google 0.079
market_return_goog = 0.0799
equity_cost = rf_rate + beta * (market_return_goog - rf_rate)

# let's pick in-between...again
equity_cost

0.09477752585521082

In [34]:
# calculating cost of debt with formula and https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/ratings.htm
# cost of debt = (risk free rate + default spread of debt) 
# or calculate from financial statements of company

t_ebit = (inc_s.loc['netIncome'][0] + 
          inc_s.loc['incomeTaxExpense'][0] + 
          inc_s.loc['interestExpense'][0])
interest_coverage = t_ebit / (inc_s.loc['interestExpense'][0])
interest_coverage
# for IC of 41 the rate is AAA with Credit default Spread (0.67%)

41.635619242579324

In [35]:
# for WACC calculation we will need market values of debt and equity
# for now we will use market capitalization as proxy for equity and total debt as proxy for debt

default_spread = 0.0067
debt_cost1 = (rf_rate + default_spread) * (1-stat_tax_rate)

total_debt = bs.loc['totalDebt'][0]
debt_cost2 = (inc_s.loc['interestExpense'][0] / total_debt) * (1 - eff_tax_rate[0])

total_equity = get_price_from_yahoo('AAPL', 2022, 12, 2, 2022, 12, 2) * inc_s.loc['weightedAverageShsOutDil'][0]
debt_share = total_debt / (total_debt + total_equity)
equity_share = total_equity / (total_debt + total_equity)

In [36]:
# for the sake of verivication let's use cost of debt that is equal to 2.04% 
debt_cost2

0.020455298436978075

In [37]:
# shares of debt and equity for wacc calculation
debt_share = total_debt / (total_debt + total_equity)
equity_share = total_equity / (total_debt + total_equity)

# wacc calculation
wacc = (debt_share * debt_cost2 * (1 - stat_tax_rate)) + (equity_share * equity_cost)
wacc

0.09105116821867841

In [38]:
equity_cost_end = rf_rate + 1 * (market_return_goog - rf_rate)
# sometimes you may see the recommendation to adjsut future wacc by making its beta = 1
# because beta tends to converge to 1 in long term 
# wacc_end = (debt_share * debt_cost2 * (1 - stat_tax_rate)) + (equity_share * equity_cost_end)
# wacc_end

## Intrinsic value according to FCFF:

In [39]:
lt_gr = 0.02
p_fcff_cf = []
df1 = fin_3.loc['FCFF','2023':]
exp_count = 1
for x in df1:
    p_fcff_cf.append(x  / (1 + wacc)**exp_count)
    exp_count += 1
tv_fcff = ((fin_3.loc['FCFF','2027'] * (1 + lt_gr)) / (wacc - lt_gr))
p_tv = tv_fcff / ((1 + wacc)**len(fin_3.loc['FCFF':,'2023':].columns))
p_fcff_cf.append(p_tv)
p_tv_fcff = tv_fcff / ((1 + wacc)**len(fin_3.loc['FCFF':,'2023':].columns))
(sum(p_fcff_cf)*1000000) / inc_s.loc['weightedAverageShsOutDil'][0]

123.2542088640865

## Intrinsic value according to FCFE:

In [40]:
p_fcfe_cf = []
df2 = fin_3.loc['FCFE','2023':]
exp_count_2 = 1
for x in df2:
    p_fcfe_cf.append(x  / (1 + equity_cost)**exp_count_2)
    exp_count_2 += 1
tv_fcfe = ((fin_3.loc['FCFE','2027'] * (1 + lt_gr)) / (equity_cost - lt_gr))
p_tv_fcfe = tv_fcfe / ((1 + equity_cost)**len(fin_3.loc['FCFF':,'2023':].columns))
p_fcfe_cf.append(p_tv_fcfe)
(sum(p_fcfe_cf)*1000000) / inc_s.loc['weightedAverageShsOutDil'][0]

134.72300532136217